# -*- coding: utf-8 -*-
"""Copy of Updated WeatherImageClassifer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1booRkfVc0L_CrVbKsO-nfTMrr5D_prNV
"""

"""
Dataset: https://data.mendeley.com/datasets/4drtyfjtfy/1

Use the given dataset and the keras package to build a neural network image classifier that categorizes an image as rainy, sunny, cloudy or sunrise.
"""

import os

from keras.layers import Activation, Conv2D, Dense, Dropout, Flatten, MaxPooling2D
from keras.models import Sequential
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.utils import get_file
from keras.layers import Input


"""# New Section"""

imagegen = ImageDataGenerator(rescale=1. / 255., rotation_range=30, horizontal_flip=True, validation_split=0.1)

# path_to_zip = get_file('weatherData.zip', origin="https://static.junilearning.com/ai_level_2/weatherData.zip", extract=True)
path_to_zip = get_file('weatherData.zip', origin="https://static.classes.jacobdanderson.net/weatherData.zip", extract=True)
# PATH = os.path.join(os.path.dirname(path_to_zip), 'weatherData')
PATH = os.path.join(os.path.dirname(path_to_zip), 'weatherData_extracted/weatherData')
train_dir = os.path.join(PATH, 'train')
validation_dir = os.path.join(PATH, 'validation')
test_dir = os.path.join(PATH, 'test')

# Batch size is 128 because it is a good balance between memory usage and training speed.
# It allows the model to learn from a sufficient number of samples in each iteration while still being efficient in terms of computation and memory consumption.
train_generator = imagegen.flow_from_directory(train_dir, class_mode="categorical", shuffle=True, batch_size=128, target_size=(224, 224))
validation_generator = imagegen.flow_from_directory(validation_dir, class_mode="categorical", shuffle=True, batch_size=128, target_size=(
	224, 224))
test_generator = imagegen.flow_from_directory(test_dir, class_mode="categorical", shuffle=False, batch_size=128, target_size=(224, 224))

# build a sequential model
# Building the model
model = Sequential()

# 3 convolutional layers
model.add(Input(shape=(224, 224, 3)))   # Input layer specifying the shape of the input images (224x224 pixels with 3 color channels)
model.add(Conv2D(32, (3, 3)))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation("relu"))
model.add(MaxPooling2D(pool_size=(2, 2)))

# Filters are like feature detectors, they work by sliding over the input image and looking for specific patterns
model.add(Conv2D(64, (3, 3)))   # This adds a convolutional layer with 64 filters, each of size 3x3
model.add(Activation("relu"))   # This applies the ReLU activation function, which introduces non-linearity to the model
model.add(MaxPooling2D(pool_size=(2, 2)))   # This reduces the spatial dimensions of the feature maps by a factor of 2 by taking the maximum value in each 2x2 block
model.add(Dropout(0.25))    # This helps prevent overfitting by randomly setting 25% of the inputs to 0 during training

# 2 hidden layers
model.add(Flatten())    # This converts the 2D feature maps into a 1D feature vector
model.add(Dense(128))   # This adds a fully connected layer with 128 neurons
model.add(Activation("relu"))   # This applies the ReLU activation function

model.add(Dense(128))   # This adds another fully connected layer with 128 neurons
model.add(Activation("relu"))   # This applies the ReLU activation function

# The output layer with 4 neurons (1 per class)
model.add(Dense(4))     # This adds the output layer with 4 neurons, one for each class (rainy, sunny, cloudy, sunrise)
model.add(Activation("softmax"))    # This applies the softmax activation function, which converts the output into probabilities for each class

# compile model
model.compile(loss='categorical_crossentropy', optimizer="adam", metrics=['accuracy'])
# fit on data for 10 epochs
# an epoch is one complete pass through the entire training dataset
model.fit(train_generator, epochs=10, validation_data=validation_generator)

# evaluate on test data
#test_generator.reset()
accuracy = model.evaluate(test_generator)[1]
print(accuracy)

examples_datagen = ImageDataGenerator(rescale=1. / 255)
examples_generator = examples_datagen.flow_from_directory(
	PATH,
	target_size=(224, 224),
	classes=['examples'],
	shuffle=False)
examples_generator.reset()
preds = model.predict(examples_generator)
predicted_classes = []
for pred in preds:
	predicted_class = -1
	max = -1
	for i in range(len(pred)):
		if pred[i] > max:
			max = pred[i]
			predicted_class = i
	predicted_classes.append(predicted_class)

for pred, name in zip(predicted_classes, examples_generator.filenames):
	print(f'Filename: {name}')
	print(f'Label: {list(train_generator.class_indices.items())[pred][0]}')
	print()
